-- function get_smods_rank_from_id(card)
--     local id = card:get_id()
--     if id > 0 then
--         for i, j in pairs(SMODS.Ranks) do
--             if j.id == id then
--                 return j
--             end
--         end
--     else
--         return SMODS.Ranks[card.base.value] or {}
--     end
-- end

-- function shuffle_card_in_deck(card)
--     -- if card.facing == 'front' then
--     --     card:flip()
--     -- end
--     local index = -1
--     for i = 1, #G.deck.cards do
--         if G.deck.cards[i] == card then
--             index = i
--             break
--         end
--     end
--     if index ~= -1 then
--         local rand_index = 1 + math.floor(#G.deck.cards * pseudorandom('shuffle_index'))
--         if rand_index == #G.deck.cards + 1 then
--             rand_index = #G.deck.cards
--         end
--         G.deck.cards[rand_index], G.deck.cards[index] = G.deck.cards[index], G.deck.cards[rand_index]
--         G.deck:set_ranks()
--     end
-- end

-- function get_card_total(cards, do_soft, bonus_total)
--     if do_soft == nil then
--         do_soft = true
--     end
--     local suits = SMODS.Suit.obj_buffer
--     local map = {}
--     local total = bonus_total or 0
--     local aces = 0
--     local variance = 0
--     local bust_limit = G.GAME.cstorm_bust_limit or 21
--     local req_count = 0
--     local soft = false
--     for i = 1, #cards do
--         local id = cards[i]:get_id()
--         local valid = true
--         if id > 0 then
--             local rank = get_smods_rank_from_id(cards[i])
--             local nominal = rank.nominal
--             if not cards[i].debuff and cards[i].ability.trading and cards[i].ability.trading.config.cstorm_hand_value then
--                 total = total + cards[i].ability.trading.config.cstorm_hand_value
--             elseif rank.key == 'Ace' then
--                 total = total + 1
--                 aces = aces + 1
--             else
--                 total = total + nominal
--             end
--             if not cards[i].debuff and cards[i].ability.trading and cards[i].ability.trading.config.cstorm_hand_aces then
--                 aces = aces + cards[i].ability.trading.config.cstorm_hand_aces
--             end
--         else
--             valid = false
--         end
--         if valid then
--             req_count = req_count + 1
--             for j = 1, #suits do
--                 if cards[i]:is_suit(suits[j], nil, true) then
--                     map[suits[j]] = map[suits[j]] or {}
--                     map[suits[j]][#map[suits[j]]+1] = cards[i] 
--                 end
--             end
--         end
--     end
--     if do_soft then
--         while (total <= bust_limit - 10) and (aces >= 1) do
--             aces = aces - 1
--             total = total + 10
--             soft = true
--         end
--         while (total <= bust_limit - 1) and (variance >= 1) do
--             variance = variance - 1
--             total = total + 1
--             soft = true
--         end
--     end
--     return {
--         total = total,
--         bust_limit = bust_limit,
--         suit_map = map,
--         card_count = req_count,
--         soft = soft
--     }
-- end

-- function hide_sum()
--     for i = 1, #G.hand.cards do
--         if G.hand.cards[i].facing == 'back' then
--             return true
--         end
--     end
--     return false
-- end

-- function check_total_over_21()
--     if G.GAME.modifiers.dungeon and G.GAME.blind.config.blind.key == 'bl_cstorm_blackjack' and not (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) then
--         G.GAME.cstorm_hand_sum_total = get_hand_sum()
--         local data = get_card_total(G.hand.cards, false)
--         if (data.total > data.bust_limit) and not G.GAME.cstorm_busted then
--             G.E_MANAGER:add_event(Event({
--                 trigger = 'immediate',
--                 func = function()
--                     if hide_sum() then
--                         play_area_status_text("Bust (??)")
--                     else
--                         play_area_status_text("Bust (" .. tostring(data.total) .. ")")
--                     end
--                     return true
--                 end
--             }))
--             G.GAME.cstorm_busted = true
--             G.GAME.cstorm_hand_perfect = false
--         elseif (data.total <= data.bust_limit) then
--             G.GAME.cstorm_busted = nil
--             G.GAME.cstorm_hand_perfect = (data.total == data.bust_limit)
--         end
--     end
-- end

-- function get_hand_sum()
--     local data = get_card_total(G.hand.cards)
--     if hide_sum() then
--         return localize("b_stand") .. ' ??'
--     elseif data.soft then
--         return localize("b_stand") .. ' S' .. tostring(data.total)
--     elseif data.total > data.bust_limit then
--         return localize("b_stand") .. ' ' .. tostring(data.total) .. 'B'
--     else
--         return localize("b_stand") .. ' ' .. tostring(data.total)
--     end
-- end

-- G.FUNCS.can_hit = function(e)
--     -- if G.hand and G.hand.highlighted and (#G.hand.highlighted == 1) and (G.GAME.current_round.discards_left > 0) then
--     --     e.config.colour = G.C.RED
--     --     e.config.button = 'discard_cards_from_highlighted'
--     if G.GAME.stood or G.GAME.cstorm_busted or (#G.deck.cards == 0) then --or (#G.hand.cards >= G.hand.config.real_card_limit)
--         e.config.colour = G.C.UI.BACKGROUND_INACTIVE
--         e.config.button = nil
--     else
--         e.config.colour = G.C.IMPORTANT
--         e.config.button = 'hit'
--     end
-- end

-- G.FUNCS.hit = function(e, no_state)
--     if not no_state then
--         G.E_MANAGER:add_event(Event({
--             trigger = 'immediate',
--             func = function()
--                 G.STATE = G.STATES.DRAW_TO_HAND
--                 G.STATE_COMPLETE = false
--                 return true
--             end
--         }))
--     end
--     local valid = true
--     local add_limit = 0
--     for i = 1, #G.hand.cards do
--         if G.hand.cards[i].calculate_exotic then
--             local result = G.hand.cards[i]:calculate_exotic({hit = true, cardarea = G.hand})
--             if result and result.add_limit then
--                 add_limit = add_limit + result.add_limit
--             end
--         end
--     end
--     if valid then
--         G.GAME.cstorm_limit = (G.hand and G.hand.cards and #G.hand.cards or 2) + 1 + add_limit
--     end
--     if G.GAME.blind.hits then
--         G.GAME.blind.hits = G.GAME.blind.hits + 1
--         if G.GAME.blind.hits == 5 then
--             G.GAME.forced_stand = true
--             G.GAME.blind.hits = 0
--         end
--         G.GAME.blind:set_text()
--     end
-- end

-- G.FUNCS.can_stand = function(e)
--     if G.GAME.stood then
--         e.config.colour = G.C.UI.BACKGROUND_INACTIVE
--         e.config.button = nil
--     else
--         e.config.colour = G.C.GREEN
--         e.config.button = 'stand'
--     end
-- end

-- G.FUNCS.stand = function(e)
--     -- Remove buttons 
--     if G.GAME.cstorm_3C_countdown_p then
--         G.GAME.cstorm_3C_countdown_p = G.GAME.cstorm_3C_countdown_p - 1
--         if G.GAME.cstorm_3C_countdown_p == 0 then
--             G.GAME.cstorm_3C_countdown_p = nil
--         end
--         full_reset_cards_debuff()
--     end
--     if G.GAME.double_mult then
--         G.GAME.negate_hand = (G.GAME.negate_hand or 1) * 2
--         G.GAME.double_mult = nil
--     end
--     G.E_MANAGER:add_event(Event({
--         trigger = 'immediate',
--         func = function()
--             G.STATE = G.STATES.HAND_PLAYED
--             G.STATE_COMPLETE = true
--             return true
--         end
--     }))
--     local y_data = get_card_total(G.hand.cards, nil, add_total)
--     local total = y_data.total
--     G.GAME.cstorm_busted = nil
--     G.GAME.stood = true
--     G.GAME.cstorm_stood_ranks = G.GAME.cstorm_stood_ranks or {}
--     G.GAME.cstorm_stood_suits = G.GAME.cstorm_stood_suits or {}
--     -- Blind Actions
--     local obj = G.GAME.blind.config.blind
--     local bl_total = 0
--     local bl_cards = {}
--     local bl_actions = {}
--     local total_list = {}
--     local stand_val = (G.GAME.cstorm_bust_limit or 21) - 4
--     if obj.get_stand_val then
--         if type(obj.get_stand_val) == 'function' then
--             stand_val = obj:get_stand_val()
--         elseif type(obj.get_stand_val) == 'number' then
--             stand_val = obj.get_stand_val
--         end
--     elseif obj.name == "Small Blind" then
--         stand_val = (G.GAME.cstorm_bust_limit or 21) - 6
--     end
--     while true do
--         local next_action = 'hit'
--         if (bl_total >= stand_val) then
--             next_action = 'stand'
--         end
--         if next_action == 'stand' then
--             table.insert(bl_actions, {'stand'})
--             break
--         elseif next_action == 'hit' then
--             local index = #G.enemy_deck.cards - #bl_cards
--             if index <= 0 then
--                 break
--             else
--                 local id = G.enemy_deck.cards[index]:get_id()
--                 table.insert(bl_cards, G.enemy_deck.cards[index])
--                 local bl_data = get_card_total(bl_cards)
--                 bl_total = bl_data.total
--                 table.insert(total_list, bl_total)
--                 table.insert(bl_actions, {'hit', G.enemy_deck.cards[index], bl_total})
--             end
--         end
--     end
--     if total > y_data.bust_limit then
--         total = -1e15
--     end
--     local bl_data = get_card_total(bl_cards, nil, add_total)
--     bl_total = bl_data.total
--     if bl_total > bl_data.bust_limit then
--         bl_total = -1e15
--     end
--     local force_push = nil
--     for i = 1, #bl_cards  do
--         if not bl_cards[i].debuff and bl_cards[i].ability.trading and (bl_cards[i].ability.trading.name == 'Sun Two') then
--             force_push = true
--             break
--         end
--     end
--     for i = 1, #G.hand.cards do
--         if not G.hand.cards[i].debuff and G.hand.cards[i].ability.trading and (G.hand.cards[i].ability.trading.name == 'Sun Two') then
--             force_push = true
--             break
--         end
--     end
--     if force_push then
--         if (bl_total ~= -1e15) then
--             bl_total = 0
--         end
--         if (total ~= -1e15) then
--             total = 0
--         end
--     end
--     SMODS.calculate_context({stand = true, cardarea = G.jokers, add_total = add_total})
--     G.E_MANAGER:add_event(Event({
--         trigger = 'immediate',
--         func = function()
--             if #bl_actions > 0 then
--                 for i = 1, #bl_actions do
--                     if bl_actions[i][1] == 'hit' then
--                         draw_card(G.enemy_deck, G.play, i*100/5, 'up', nil, bl_actions[i][2])
--                         force_up_status_text = true
--                         local color = G.C.FILTER
--                         if bl_actions[i][3] > (bl_data.bust_limit) then
--                             color = G.C.RED
--                         elseif bl_actions[i][3] >= stand_val then
--                             color = G.C.GREEN
--                         end
--                         card_eval_status_text(bl_actions[i][2], 'extra', nil, nil, nil, {message = tostring(bl_actions[i][3]), colour = color})
--                         force_up_status_text = nil
--                     elseif bl_actions[i][1] == 'stand' then
--                         if G.GAME.cstorm_3C_countdown_e then
--                             G.GAME.cstorm_3C_countdown_e = G.GAME.cstorm_3C_countdown_e - 1
--                             if G.GAME.cstorm_3C_countdown_e == 0 then
--                                 G.GAME.cstorm_3C_countdown_e = nil
--                             end
--                             full_reset_cards_debuff()
--                         end
--                     end
--                 end
--             end
--             delay(0.5)
--             -- if (bl_total > total) or (not next(SMODS.find_card('j_hit_tiebreaker')) and (bl_total == total)) then
--             --     local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.hand.cards)
--             --     for i = 1, #G.hand.cards do
--             --         if G.hand.cards[i].seal == 'hit_blue' then
--             --             update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, nopulse = nil, delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
--             --             level_up_hand(G.hand.cards[i], text)
--             --             update_hand_text({nopulse = true, delay = 0}, {mult = 0, chips = 0, level = '', handname = ''})
--             --             delay(0.1)
--             --         end
--             --     end
--             -- end
--             -- if (bl_total < total) or (next(SMODS.find_card('j_hit_tiebreaker')) and (bl_total == total)) then
--             --     if bl_total == -1e15 then
--             --         if (next(SMODS.find_card('j_hit_tiebreaker')) and (bl_total == total)) then
--             --             play_area_status_text("Win (Bust = Bust)")
--             --         else
--             --             play_area_status_text("Win (" .. tostring(total) .. " > Bust)")
--             --         end
--             --     else
--             --         if (next(SMODS.find_card('j_hit_tiebreaker')) and (bl_total == total)) then
--             --             play_area_status_text("Win (" .. tostring(total) .. " = " .. tostring(bl_total) .. ")")
--             --         else
--             --             play_area_status_text("Win (" .. tostring(total) .. " > " .. tostring(bl_total) .. ")")
--             --         end
--             --     end
--             --     SMODS.calculate_context({post_stand = true, cardarea = G.jokers, add_total = add_total , won = true})
--             --     if G.GAME.blind and (G.GAME.blind.name == "hit_The Needle") and not G.GAME.blind.disabled then
--             --         G.E_MANAGER:add_event(Event({
--             --             trigger = 'immediate',
--             --             func = function()
--             --                 G.GAME.blind:disable()

--             --                 return true
--             --             end
--             --         }))
--             --     end
--                 G.GAME.cstorm_limit = 2
--                 ease_hands_played(1)
--                 G.E_MANAGER:add_event(Event({
--                     trigger = 'immediate',
--                     func = function()
--                         for i = 1, #G.play.cards do
--                             draw_card(G.play, G.enemy_discard, i*100/5, 'up')
--                         end
--                         G.E_MANAGER:add_event(Event({
--                             trigger = 'immediate',
--                             func = function()
--                                 for i = 1, #G.hand.cards do
--                                     if not G.hand.cards[i].highlighted then
--                                         G.hand:add_to_highlighted(G.hand.cards[i])
--                                     end
--                                     local id = G.hand.cards[i]:get_id()
--                                     local suit = SMODS.Suits[G.hand.cards[i].base.suit] or {}
--                                     if id > 0 then
--                                         local rank = get_smods_rank_from_id(G.hand.cards[i])
--                                         G.GAME.cstorm_stood_ranks[rank.key] = (G.GAME.cstorm_stood_ranks[rank.key] or 1) + 1
--                                     end
--                                     if G.hand.cards[i]:is_suit(suit.key) then
--                                         G.GAME.cstorm_stood_suits[suit.key] = (G.GAME.cstorm_stood_suits[suit.key] or 1) + 1
--                                     end
--                                 end
--                                 G.FUNCS.play_cards_from_highlighted()
--                                 G.GAME.cstorm_busted = nil
--                                 G.E_MANAGER:add_event(Event({
--                                     trigger = 'immediate',
--                                     func = function()
--                                         G.GAME.stood = nil
--                                         return true
--                                     end
--                                 }))
--                                 return true
--                             end
--                         }))
--                         return true
--                     end
--                 }))
--             if bl_total == total then
--                 if bl_total == -1e15 then
--                     if hide_sum() then
--                         play_area_status_text("Push (?? = Bust)")
--                     else
--                         play_area_status_text("Push (Bust = Bust)")
--                     end
--                 else
--                     if hide_sum() then
--                         play_area_status_text("Push (?? = " .. tostring(bl_total) .. ")")
--                     else
--                         play_area_status_text("Push (" .. tostring(total) .. " = " .. tostring(bl_total) .. ")")
--                     end
--                 end
--                 SMODS.calculate_context({post_stand = true, cardarea = G.jokers, add_total = add_total , won = false})
--                 G.GAME.cstorm_limit = 2
--                 G.E_MANAGER:add_event(Event({
--                     trigger = 'immediate',
--                     func = function()
--                         for i = 1, #G.play.cards do
--                             draw_card(G.play, G.enemy_discard, i*100/5, 'up')
--                         end
--                         for i = #G.hand.cards, 1, -1 do
--                             if (G.hand.cards[i].ability.name ~= 'Garnet Card') or G.hand.cards[i].debuff then
--                                 draw_card(G.hand, G.discard, i*100/5, 'up', nil, G.hand.cards[i])
--                             end
--                         end
--                         G.E_MANAGER:add_event(Event({
--                             trigger = 'immediate',
--                             func = function()
--                                 G.STATE_COMPLETE = false
--                                 return true
--                             end
--                         }))
--                         G.E_MANAGER:add_event(Event({
--                             trigger = 'immediate',
--                             func = function()
--                                 G.GAME.stood = nil
--                                 return true
--                             end
--                         }))
--                         return true
--                     end
--                 }))
--             elseif bl_total > total then
--                 if total == -1e15 then
--                     if hide_sum() then
--                         play_area_status_text("Loss (?? < " .. tostring(bl_total) .. ")")
--                     else
--                         play_area_status_text("Loss (Bust < " .. tostring(bl_total) .. ")")
--                     end
--                 else
--                     if hide_sum() then
--                         play_area_status_text("Loss (?? < " .. tostring(bl_total) .. ")")
--                     else
--                         play_area_status_text("Loss (" .. tostring(total) .. " < " .. tostring(bl_total) .. ")")
--                     end
--                 end
--                 SMODS.calculate_context({post_stand = true, cardarea = G.jokers, add_total = add_total , won = false})
--                 G.GAME.cstorm_limit = 2
--                 ease_hands_played(-1)
--                 G.E_MANAGER:add_event(Event({
--                     trigger = 'immediate',
--                     func = function()
--                         G.E_MANAGER:add_event(Event({
--                             trigger = 'immediate',
--                             func = function()
--                                 for i = #G.hand.cards, 1, -1 do
--                                     if (G.hand.cards[i].ability.name ~= 'Garnet Card') or G.hand.cards[i].debuff then
--                                         draw_card(G.hand, G.discard, i*100/5, 'up', nil, G.hand.cards[i])
--                                     end
--                                 end
--                                 G.GAME.negate_hand = (G.GAME.negate_hand or 1) * -0.5
--                                 G.E_MANAGER:add_event(Event({
--                                     trigger = 'immediate',
--                                     func = function()
--                                         for i = 1, #G.jokers.cards do
--                                             G.jokers.cards[i]:set_debuff()
--                                         end
--                                         local save_played = {}
--                                         local save_played_round = {}
--                                         for i, j in pairs(G.GAME.hands) do
--                                             if j and j.played then
--                                                 save_played[i] = j.played
--                                                 save_played_round[i] = j.played_this_round
--                                             end
--                                         end
--                                         G.FUNCS.evaluate_play()
--                                         for i, j in pairs(save_played) do
--                                             G.GAME.hands[i].played_this_round = save_played[i]
--                                             G.GAME.hands[i].played = save_played_round[i]
--                                         end
--                                         return true
--                                     end
--                                 }))
--                                 G.E_MANAGER:add_event(Event({
--                                     trigger = 'after',
--                                     delay = 0.1,
--                                     func = function()
--                                         G.GAME.hands_played = G.GAME.hands_played + 1
--                                         G.GAME.current_round.hands_played = G.GAME.current_round.hands_played + 1
--                                         return true
--                                     end
--                                 }))
--                                 G.E_MANAGER:add_event(Event({
--                                     trigger = 'immediate',
--                                     func = function()
--                                         local play_count = #G.play.cards
--                                         local it = 1
--                                         for k, v in ipairs(G.play.cards) do
--                                             if (not v.shattered) and (not v.destroyed) then 
--                                                 draw_card(G.play,G.enemy_discard, it*100/play_count,'down', false, v)
--                                                 it = it + 1
--                                             end
--                                         end
--                                         return true
--                                     end
--                                 }))
--                                 G.E_MANAGER:add_event(Event({
--                                     trigger = 'immediate',
--                                     func = function()
--                                         G.STATE_COMPLETE = false
--                                         return true
--                                     end
--                                 }))
--                                 G.GAME.cstorm_busted = nil
--                                 G.E_MANAGER:add_event(Event({
--                                     trigger = 'immediate',
--                                     func = function()
--                                         G.GAME.stood = nil
--                                         return true
--                                     end
--                                 }))
--                                 return true
--                             end
--                         }))
--                         return true
--                     end
--                 }))
--             end
--             if #G.enemy_deck.cards - #bl_cards <= 0 then
--                 G.E_MANAGER:add_event(Event({
--                     trigger = 'immediate',
--                     func = function()
--                         for i = 1, #G.enemy_discard.cards do
--                             draw_card(G.enemy_discard, G.enemy_deck, i*100/5, 'up')
--                         end
--                         return true
--                     end
--                 }))
--                 G.E_MANAGER:add_event(Event({
--                     trigger = 'immediate',
--                     func = function()
--                         G.enemy_deck:shuffle('enemy_deck')
--                         return true
--                     end
--                 }))
--             end
--             return true
--         end
--     }))
-- end

-- local old_draw_from_deck = G.FUNCS.draw_from_deck_to_hand
-- G.FUNCS.draw_from_deck_to_hand = function(e)
--     if G and G.GAME and G.GAME.modifiers and G.GAME.modifiers.dungeon then
--         if G.GAME.blind.config.blind.key == 'bl_cstorm_blackjack' then
--             local hand_space =  math.min(2, math.max(0, (G.GAME.cstorm_limit or 2) - #G.hand.cards))
--             if (#G.hand.cards ~= 0) and (hand_space == 2) then
--                 hand_space = 1
--             end
--             if hand_space >= 1 then
--                 local i = 1
--                 local j = 0
--                 while ((#G.hand.cards ~= 0) and (hand_space == 1) and (i + j <= hand_space)) or ((hand_space ~= 1) and (i <= hand_space))  do
--                     if not G.deck.cards[#G.deck.cards - i - j + 1] then
--                         break
--                     end
--                     if G.deck.cards[#G.deck.cards - i - j + 1] and G.GAME.suits_drawn then
--                         for i2, j2 in pairs(SMODS.Suits) do
--                             if G.deck.cards[#G.deck.cards - i - j + 1]:is_suit(j2.key) then
--                                 G.GAME.suits_drawn[j2.key] = true
--                             end
--                         end
--                         local count = 0
--                         for i2, j2 in pairs(G.GAME.suits_drawn) do
--                             count = count + 1
--                         end
--                         if count >= 4 then
--                             G.GAME.suits_drawn = nil
--                         end
--                     end
--                     if G.deck.cards[#G.deck.cards - i - j + 1] then
--                         G.deck.cards[#G.deck.cards - i - j + 1]:set_sprites()
--                     end
--                 end
--             end
--         end
--     else
--         old_draw_from_deck(e)
--     end
-- end

-- function set_blackjack_mode()
--     G.GAME.modifiers = G.GAME.modifiers or {}
--     if G.GAME.modifiers.dungeon then
--         return true
--     end

--     G.GAME.modifiers.dungeon = true
--     for hand, j in pairs(G.GAME.hands) do
--         G.GAME.hands[hand].visible = false
--         if G.GAME.hands[hand].bj_mode then
--             G.GAME.hands[hand].visible = true
--         end
--     end
--     G.E_MANAGER:add_event(Event({
--         func = function()
--             G.hand.config.real_card_limit = 6
--             G.hand.config.card_limit = 6
--             return true
--         end
--     }))
-- end

-- local old_buttons = create_UIBox_buttons
-- function create_UIBox_buttons()
--     local t = old_buttons()
--     if G and G.GAME and G.GAME.modifiers and G.GAME.blind.config.blind.key == 'bl_cstorm_blackjack' then
--         local index = 3
--         if G.SETTINGS.play_button_pos ~= 1 then
--             index = 1
--         end
--         local button = t.nodes[index]
--         button.nodes[1].nodes[1].config.text = nil
--         button.nodes[1].nodes[1].config.ref_value = 'cstorm_discard_button'
--         button.nodes[1].nodes[1].config.ref_table = G.GAME
--         button.config.button = 'hit'
--         button.config.func = 'can_hit'
--     end
--     if G and G.GAME and G.GAME.blind.config.blind.key == 'bl_cstorm_blackjack' then --and G.GAME.modifiers
--         local index = 1
--         if G.SETTINGS.play_button_pos ~= 1 then
--             index = 3
--         end
--         G.GAME.cstorm_hand_sum_total = G.GAME.cstorm_hand_sum_total or '???'
--         local button = t.nodes[index]
--         button.nodes[1].nodes[1].config.text = nil
--         button.nodes[1].nodes[1].config.ref_value = 'cstorm_hand_sum_total'
--         button.nodes[1].nodes[1].config.ref_table = G.GAME
--         button.config.button = 'stand'
--         button.config.func = 'can_stand'
--     end
--     return t
-- end


-- SMODS.Blind{
--     key = "blackjack",
--     --atlas = "blinds",
-- 	pos = { x = 9, y = 0 },
-- 	dollars = 5,
-- 	mult = 1,
-- 	boss = { min = 1, max = 10 },
-- 	boss_colour = HEX('0E571A'),
-- 	config = {},
--     apply = function(self)
--         set_blackjack_mode()
--         G.GAME.cstorm_bust_limit = 21
--     end,
-- }