CSTORM.riddles = {
	{ question = { "What has hands but can't clap?" }, answer = "A Clock" },
	{ question = { "What has many teeth but can't bite?" }, answer = "A Comb" },
	{ question = { "What is so fragile that just saying its name breaks it?" }, answer = "Silence" },
	{ question = { "Who can shave 25 times a day but still have a beard?" }, answer = "A Barber" },
	{ question = { "I know a word of letters three.", "Add two and fewer there will be." }, answer = "The Word 'few'" },
	{ question = { "What is harder to catch the faster you run?" }, answer = "Your Breath" },
	{ question = { "Every night I'm told what to do,", "and each morning I do what I'm told.", "But I still don't escape your scold.", "What am I?" }, answer = "An Alarm Clock" },
	{ question = { "What gets wet while drying?" }, answer = "A Towel" },
	{ question = { "I follow you all the time and copy your every move,", "but you can't touch me or catch me.", "What am I?" }, answer = "Your Shadow" },
	{ question = { "People buy me to eat", "but never eat me.", "What am I?" }, answer = "Plates and Cutlery" },
	{ question = { "I'm tall when I'm young", "and I'm short when I'm old.", "What am I? " }, answer = "A Candle" },
	{ question = { "I have no feet,", "no hands,", "no wings,", "but I climb to the sky.", "What am I?" }, answer = "Smoke" },
	{ question = { "The maker doesn't want it.", "The buyer doesn't use it.", "The user doesn't know it.", "What am I?" }, answer = "A Coffin" },
	{ question = { "A plane crashed off the coast of Mexico", "and every single person died,", "yet there were two survivors.", "How could that happen?" }, answer = "The survivors were a Couple" },
	{ question = { "There is a house.", "A person enters this house blind", "but exits it seeing.", "What is it?" }, answer = "A School" },
	{ question = { "I have billions of eyes,",  "yet I live in darkness.", "I have millions of ears,", "yet only four lobes.", "I have no muscle,", "yet I rule two hemispheres.", "What am I?" }, answer = "Human Brain" },
	{ question = { "What can jump higher than a building?" }, answer = "Anything that can jump because buildings don't jump." },
	{ question = { "A boy and a doctor were fishing.", "The boy is the doctor's son", "but the doctor is not the boy's father.", "Who is the doctor?" }, answer = "The boy's mother" },
	{ question = { "What is more useful when it is broken?" }, answer = "An Egg" },
	{ question = { "Simon's dad had four sons:", "March, April, and May.", "What is the name of the fourth son?" }, answer = "Simon" },
	{ question = { "What word is spelled wrong in the dictionary?" }, answer = "The Word 'Wrong'" },
	{ question = { "What is seen in the middle of March and April", "that can't be seen at the beginning or end of either month?" }, answer = "It's the letter 'R'" },
	{ question = { "This belongs to you, but everyone else uses it." }, answer = "Your Name" },
	{ question = { "What can you hold in your right hand,", "but never in your left hand?" }, answer = "Your left Hand" },
	{ question = { "A group of bunnies were having a birthday party.", "What kind of music were they listening to?" }, answer = "Hip Hop Music" },
	{ question = { "I am white when I am dirty,", "and black when I am clean.", "What am I?" }, answer = "A Blackboard" },
	{ question = { "An elephant in Africa is called Lala.", "An elephant in Asia is called Lulu.", "What do you call an elephant in Antarctica?" }, answer = "You'll call that elephant lost" },
	{ question = { "If the prisoner tells a lie he'll be hanged,", "if he tells the truth he'll be beheaded.", "What can he say to save himself?" }, answer = "Don't say anything" },
	{ question = { "The rich men want it,", "the wise men know it,", "the poor all need it,", "the kind men show it." }, answer = "Love" },
	{ question = { "Why was Karl Marx buried at Highgate Cemetery in London?" }, answer = "Because he was dead" },
	{ question = { "Where did the sheep go on vacation?" }, answer = "The Baaaahamas" },
	{ question = { "What is a frog's favorite year?" }, answer = "The Leap Year" },
	{ question = { "What do you call a fairy that hasn't taken a bath?" }, answer = "Stinker Bell" },
	{ question = { "What has one horn and gives milk?" }, answer = "A Milk Truck" },
	{ question = { "What do snowmen eat for breakfast?" }, answer = "Snowflakes" },
	{ question = { "What rock group consists of four famous men,", "but none of them sing?" }, answer = "Mount Rushmore" },
	{ question = { "How can you drop a raw egg", "onto a concrete floor", "without cracking it?" }, answer = "Concrete floors are very hard to crack" },
	{ question = { "What do you call a dog with no legs?" }, answer = "It doesn't matter. He can't come to you anyway." },
	{ question = { "I am a three-digit number.", "My second digit is 4 times bigger", "than the third digit.", "My first digit is 3 less", "than my second digit.", "Guess the number?" }, answer = "141 or 582" },
	{ question = { "If eleven plus two equals one,", "what does nine plus five equal?" }, answer = "11 o'clock plus 2 hours = 1 o'clock, 9 o'clock plus 5 hours = 2 o'clock" },
	{ question = { "How much will a 38-degree angle measure", "when looked at under a microscope", "that magnifies ten times?" }, answer = "The angle won't change. It will still be 38 degrees." },
	{ question = { "How do you make the number 7 even", "without addition, subtraction, multiplication, or division?" }, answer = "Drop the 'S'" },
	{ question = { "TEN = 20, 5, 14", " ", "MEN = 13, 5, 14", " ", "What do WOMEN equal using the same logic? " }, answer = "WOMEN = 23, 15, 13, 5, 14. The numbers represent the letter's position in English alphabets." },
	{ question = { "It's full of keys but can't open any door.", "What is it?" }, answer = "A Piano" },
	{ question = { "Where will you find Friday before Thursday?" }, answer = "In a Dictionary" },
	{ question = { "If you throw a white stone into a red sea,", "what will happen to it?" }, answer = "It will get wet (or sink)" },
	{ question = { "Which day is near to come but never comes?" }, answer = "Tomorrow" },
	{ question = { "It is the beginning of eternity,", "the end of time and space.", "It is the start of every end,", "the end of every place." }, answer = "The letter 'E'" },
	{ question = { "Which seven-letter word", "contains dozens of letters?" }, answer = "Mailbox" },
}

--Boss with only Balatro riddles
CSTORM.boss_riddles = {
	Jokers = {
		{ question = { "I am the beginning,", "yet offer nothing special.", "Four is my gift,", "simple and true.", "What am I?" }, answer = "Joker" },
		{ question = { "My vice is clear in my very name.", "I hunger for wealth's sparkle", "and reward those who share my obsession.", "What am I?" }, answer = "Greedy Joker" },
		{ question = { "I am driven by passion,", "named for one of the seven sins.", "Romance fuels my power.", "What am I?" }, answer = "Lusty Joker" },
		{ question = { "Anger is my essence,", "darkness my domain.", "The blackest suit ignites my fury.", "What am I?" }, answer = "Wrathful Joker" },
		{ question = { "Excess is my nature,", "consumption my desire.", "I feast endlessly on the suit of war.", "What am I?" }, answer = "Gluttonous Joker" },
		{ question = { "I find happiness in symmetry's simplest form.", "Two of a kind brings me joy.", "What am I?" }, answer = "Jolly Joker" },
		{ question = { "Madness takes hold when three become one.", "Triplets drive me to ecstasy.", "What am I?" }, answer = "Zany Joker" },
		{ question = { "I am unhinged by perfect balance.", "Two pairs send me into frenzy.", "What am I?" }, answer = "Mad Joker" },
		{ question = { "Order in chaos excites me beyond reason.", "Five in sequence breaks my mind.", "What am I?" }, answer = "Crazy Joker" },
		{ question = { "I am amused by uniformity's embrace.", "When all wear the same colors, I chuckle.", "What am I?" }, answer = "Droll Joker" },
		{ question = { "My treasures hide until twins appear.", "Then I reveal my modest hoard.", "What am I?" }, answer = "Sly Joker" },
		{ question = { "Cunning guides my generosity.", "Three identical faces unlock my vault.", "What am I?" }, answer = "Wily Joker" },
		{ question = { "Intelligence dictates my gifts.", "Double duality triggers my calculated response.", "What am I?" }, answer = "Clever Joker" },
		{ question = { "I scheme in silence until perfection aligns.", "Sequential harmony reveals my fortune.", "What am I?" }, answer = "Devious Joker" },
		{ question = { "My artistry emerges when unity is complete.", "Matching suits inspire my creation.", "What am I?" }, answer = "Crafty Joker" },
		{ question = { "Minimalism is my philosophy.", "The fewer you show,", "the more I give.", "What am I?" }, answer = "Half Joker" },
		{ question = { "I am an empty framework that grows with absence.", "Vacant spaces fuel my power.", "What am I?" }, answer = "Joker Stencil" },
		{ question = { "I break ancient rules with modern efficiency.", "What once required five now needs only four.", "What am I?" }, answer = "Four Fingers" },
		{ question = { "I speak without words,", "copying silent performances.", "Your hand becomes my stage.", "What am I?" }, answer = "Mime" },
		{ question = { "I offer what you lack", "but charge for tomorrow.", "Danger lurks in my convenience.", "What am I?" }, answer = "Credit Card" },
		{ question = { "Ritual sacrifice empowers my blade.", "My neighbors feed my growing strength.", "What am I?" }, answer = "Ceremonial Dagger" },
		{ question = { "I wave proudly for unused potential.", "Conservation multiplies my display.", "What am I?" }, answer = "Banner" },
		{ question = { "I reach my peak only in total emptiness.", "When all is spent, I shine brightest.", "What am I?" }, answer = "Mystic Summit" },
		{ question = { "I am a sculptor of permanence.", "Each challenge adds weight to your collection.", "What am I?" }, answer = "Marble Joker" },
		{ question = { "Faithfulness is rewarded exponentially.", "Count to six, and I'll multiply your devotion.", "What am I?" }, answer = "Loyalty Card" },
		{ question = { "I divine the future through a number's power.", "Play my symbol, and magic may appear.", "What am I?" }, answer = "8 Ball" },
		{ question = { "I am error made manifest.", "My value fluctuates like a broken machine.", "What am I?" }, answer = "Misprint" },
		{ question = { "I save my greatest magic for endings.", "When darkness falls, everything echoes.", "What am I?" }, answer = "Dusk" },
		{ question = { "I champion the weak and forgotten.", "Your lowest becomes my highest strength.", "What am I?" }, answer = "Raised Fist" },
		{ question = { "I bring disorder to commerce.", "Randomness bows to my influence.", "What am I?" }, answer = "Chaos The Clown" },
		{ question = { "I follow nature's most famous sequence.", "Only certain numbers sing to my soul.", " What am I?" }, answer = "Fibonacci" },
		{ question = { "My strength mirrors the metal in your possession.", "Industrial power flows through me.", "What am I?" }, answer = "Steel Joker" },
		{ question = { "I terrify the noble and proud.", "Royalty trembles before my frightening visage.", "What am I?" }, answer = "Scary Face" },
		{ question = { "I am a concept that feeds on my own kind.", "More jesters mean stronger abstraction.", "What am I?" }, answer = "Abstract Joker" },
		{ question = { "Patience is virtue,", "restraint is wealth.", "Save what others waste,", "earn what others lose.", "What am I?" }, answer = "Delayed Gratification" },
		{ question = { "I corrupt the natural order.", "Low numbers transcend their limitations.", "What am I?" }, answer = "Hack" },
		{ question = { "I see nobility where others see commoners.", "My vision transforms reality.", "What am I?" }, answer = "Pareidolia" },
		{ question = { "I am sweetness with an expiration date.", "My generosity comes with mortal risk.", "What am I?" }, answer = "Gros Michel" },
		{ question = { "I prefer balance and order.", "Only even numbers earn my favor.", "What am I?" }, answer = "Even Steven" },
		{ question = { "I celebrate the irregular and unique.", "Odd numbers receive my strange blessing.", "What am I?" }, answer = "Odd Todd" },
		{ question = { "Knowledge is power, and I honor the highest rank.", "What am I?" }, answer = "Scholar" },
		{ question = { "I turn social connections into profit.", "Networking sometimes pays dividends.", "What am I?" }, answer = "Business Card" },
		{ question = { "I am explosion born of experience.", "The more you've walked this path,", "the brighter I burn.", "What am I?" }, answer = "Supernova" },
		{ question = { "I am a journey without destination.", "Avoiding faces builds my momentum.", "What am I?" }, answer = "Ride the Bus" },
		{ question = { "I launch possibilities into higher realms.", "Sometimes your hands transcend their limits.", "What am I?" }, answer = "Space Joker" },
		{ question = { "I am potential waiting to hatch.", "Each cycle increases my future worth.", "What am I?" }, answer = "Egg" },
		{ question = { "I steal to give, take to grant.", "More chances cost you flexibility.", "What am I?" }, answer = "Burglar" },
		{ question = { "I teach through monochrome discipline.", "Unity of darkness multiplies learning.", "What am I?" }, answer = "Blackboard" },
		{ question = { "I am an athlete who gains strength from linear victories.", "Order fuels my endurance.", "What am I?" }, answer = "Runner" },
		{ question = { "I begin strong but weaken with time.", "Each performance diminishes my essence.", "What am I?" }, answer = "Ice Cream" },
		{ question = { "I am the code of life itself.", "Isolation triggers perfect replication.", "What am I?" }, answer = "DNA" },
		{ question = { "I democratize importance.", "In my presence,", "everyone matters equally.", "What am I?" }, answer = "Splash" },
		{ question = { "My strength comes from untapped potential.", "The deeper your reserves,", "the more I contribute.", "What am I?" }, answer = "Blue Joker" },
		{ question = { "I have supernatural sight for one specific number.", "Show me solitude,", "and I'll grant spectral power.", "What am I?" }, answer = "Sixth Sense" },
		{ question = { "I am a celestial map that grows with cosmic wisdom.", "Planetary knowledge fuels my radiance.", "What am I?" }, answer = "Constellation" },
		{ question = { "" }, answer = "" },
		{ question = { "" }, answer = "" },
		{ question = { "" }, answer = "" },
		{ question = { "" }, answer = "" },
		{ question = { "" }, answer = "" },
		{ question = { "" }, answer = "" },
		{ question = { "I'm royal by birth", "but I multiply your worth.", "The more crowns I see,", "the stronger you'll be.", "What am I?" }, answer = "The Baron" },
	},
}
